---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Note: If you are receiving a status of INVALID for a TLE file. Paste the TLE file here to see what is wrong: https://www.whatswrongwithmytle.com/
# It is sometimes an incorrect checksum that can be fixed using this site by simply changing the last digit to the correct checksum
# For information related to the TLE format: https://celestrak.org/NORAD/documentation/tle-fmt.php
# For information related to the supported OEM format: https://docs.aws.amazon.com/ground-station/latest/ug/providing-custom-ephemeris-data.html

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates CPE pipeline resources 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Ground Station Parameters"
        Parameters:
          - SatelliteName
          - NoradId
          - TleExpiration
          - NotificationEmail
          - SatelliteId

Parameters:

  TleExpiration:
    Description: Number of days that the ephemeris will be valid. 
    Type: Number
    Default: 6

  SatelliteName:
    Type: String
    Description: Name of the satellite, for which you will be updating ephemeris. MUST BE LOWER CASE
    Default: "jpss-1"

  NoradId:
    Type: String
    Description: NoradId of the satellite, for which you will be updating ephemeris. 
    Default: '43013'

  NotificationEmail:
    Default: 'someone@somewhere.com'
    Description: "Email address to receive ephemeris update status."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"
    ConstraintDescription: "Must be a valid email adress"

  SatelliteId:
    Type: String
    Description: The UUID of the satellite as assigned by the Ground Station Service. Leave empty to automatically obtain the ID using the NORAD ID.
    Default: ""

Resources:

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: alias/aws/sns
      DisplayName:
        Fn::Join:
          - "-"
          - - "GroundStation-CPE-Status"
            - !Ref SatelliteName
      Subscription:
        - Endpoint: !Ref NotificationEmail
          Protocol: "email"

  Key:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: "KMS Key for bucket objects"
      EnableKeyRotation: true
      KeyPolicy: 
        Version: 2012-10-17
        Statement:
          - Sid: Enable full access to root
            Effect: Allow
            Action: 'kms:*'
            Resource: '*'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
  
  ConfigBucket:
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: S3 logging is not required on this bucket as it contains only transient data
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${AWS::AccountId}-config-bucket-${SatelliteName}-${AWS::Region}'
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Ref Key
  
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConfigBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Condition:
              Bool:
                'aws:SecureTransport': false
            Effect: Deny
            Principal: '*'
            Resource: !Sub 'arn:aws:s3:::${AWS::AccountId}-config-bucket-${SatelliteName}-${AWS::Region}/*'
            Sid: DenyUnencryptedConnections


  AllowS3ToCallLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref CpeUpdateLambda
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt ConfigBucket.Arn
      SourceAccount: !Sub '${AWS::AccountId}'

  CpeUpdateLambda:
    Type: 'AWS::Serverless::Function'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: Function is not required in a VPC; deploying outside a VPC simplifies deployment
    PackageType: Zip
    Properties:
      ReservedConcurrentExecutions: 10
      Events:
        Upload:
          Type: S3
          Properties:
            Bucket: !Ref ConfigBucket
            Events: 's3:ObjectCreated:*'
      InlineCode:
          |
          import os
          import sys
          import json
          import urllib.parse
          from time import sleep
          from datetime import datetime, timedelta, timezone

          # Force import latest version of boto3
          sys.path.insert(0,"/opt/gs-boto")
          print("sys.path:"+str(sys.path))

          from pip._internal import main

          main(['install', '-I', '-q', 'boto3', '--target', '/tmp/', '--no-cache-dir', '--disable-pip-version-check'])
          sys.path.insert(0,'/tmp/')

          import boto3
          import botocore
          from botocore.exceptions import ClientError

          def handler(event, context):
              print(boto3.__version__)

          print("boto3 version:"+boto3.__version__)
          print("botocore version:"+botocore.__version__)

          s3 = boto3.client('s3')
          gs = boto3.client('groundstation')

          def handler(event, context):
            print(event)
            for record in event['Records']:
              eventName = record['eventName']
              bucket = record['s3']['bucket']['name']
              key = record['s3']['object']['key']
              execution_time = record['eventTime']

              daysToLive = os.environ['EXPIRATION']
              satellite_id = os.environ['SATELLITE_ID']
              norad_id = os.environ['NORAD_ID']
              tle_key = os.environ['TLE_KEY']
              oem_key = os.environ['OEM_KEY']
              s3_bucket = os.environ['BUCKET']

              if satellite_id == '':
                print(f"Getting Satellite ID from NORAD ID: {norad_id}")
                satellites = gs.list_satellites()['satellites']
                satellite_id = next((s['satelliteId'] for s in satellites if str(s['noradSatelliteID']) == norad_id), None)
              
              if record['eventName'].startswith('ObjectCreated') and bucket == s3_bucket and key == tle_key:

                print(f"Norad Id: {norad_id}")
                print(f"S3 Bucket: {s3_bucket}")
                print(f"Satellite Id: {satellite_id}")
                print(f"Getting {key} from {bucket}")

                resp = s3.get_object(Bucket=bucket, Key=key)
                lines = list(resp['Body'].iter_lines())
                # daysToLive = os.environ['EXPIRATION']
                # satellite_id = os.environ['SATELLITE_ID']
                # norad_id = os.environ['NORAD_ID']

                start_time = datetime.utcnow() - timedelta(days=1)
                end_time = datetime.utcnow() + timedelta(days=int(daysToLive))
                print(f"Start: {start_time}")
                print(f"End: {end_time}")
                tle = json.dumps([{
                  "tleLine1": lines[1].decode('UTF-8'),
                  "tleLine2": lines[2].decode('UTF-8'),
                  "validTimeRange": {
                    "startTime": start_time.isoformat(),
                    "endTime": end_time.isoformat()
                  }
                }], indent=2)
                json_key = f"{key}.json"
                print(f"Uploading TLE data to: s3://{bucket}/{json_key}")
                s3.put_object(
                  Bucket=bucket,
                  Key=json_key,
                  Body=tle
                )

                print(f"Creating Ephemeris from file: {tle_key}")
                try:
                  result = gs.create_ephemeris(
                    name=f"{norad_id}",
                    satelliteId=satellite_id,
                    expirationTime=end_time,
                    enabled=True,
                    kmsKeyArn=os.environ['KMS_KEY'],
                    ephemeris = {
                      "tle": {
                        "s3Object": {
                          "bucket": bucket,
                          "key": json_key
                        }
                      }
                    }
                  )
                except Exception as e:
                  print(f"Error creating Ephemeris from file: {tle_key}. Error: {e}")
                  return {'ephemeris_id': None}

                ephem_id = result['ephemerisId']
                print(f"Polling status for ${ephem_id}")
                resp = gs.describe_ephemeris(ephemerisId=ephem_id)
                status = resp['status']
                print(status)
                while status == 'VALIDATING':
                  sleep(5)
                  resp = gs.describe_ephemeris(ephemerisId=ephem_id)
                  status = resp['status']
                  print(f"Status: {status}")

                print("Response from describe_ephemeris: ")
                print(resp)

                sendSNS(key, ephem_id, status, satellite_id, execution_time)
                
                return {'ephemeris_id': ephem_id, status: status}
              
              
              elif record['eventName'].startswith('ObjectCreated') and bucket == s3_bucket and key == oem_key:

                print(f"Norad Id: {norad_id}")
                print(f"S3 Bucket: {s3_bucket}")
                print(f"Satellite Id: {satellite_id}")
                print(f"Getting {key} from {bucket}")

                start_time = datetime.utcnow() - timedelta(days=1)
                end_time = datetime.utcnow() + timedelta(days=int(daysToLive))
                print(f"Start: {start_time}")
                print(f"End: {end_time}")
                
                key = urllib.parse.unquote_plus(event['Records'][0]['s3']['object']['key'], encoding='utf-8')
              
                print(f"Creating Ephemeris from file: {oem_key}")
                try:
                  result = gs.create_ephemeris(
                    name='Norad Id',
                    satelliteId=satellite_id,
                    enabled=True,
                    expirationTime=end_time,
                    kmsKeyArn=os.environ['KMS_KEY'],
                    ephemeris = {
                        "oem":{
                            "s3Object": {
                                "bucket": bucket,
                                "key": key
                            }
                        }
                    }
                  )
                except Exception as e:
                  print(f"Error creating Ephemeris from file: {oem_key}. Error: {e}")
                  return {'ephemeris_id': None}

                ephem_id = result['ephemerisId']
                print(f"Polling status for ${ephem_id}")
                resp = gs.describe_ephemeris(ephemerisId=ephem_id)
                status = resp['status']
                print(status)
                while status == 'VALIDATING':
                  sleep(5)
                  resp = gs.describe_ephemeris(ephemerisId=ephem_id)
                  status = resp['status']
                  print(status)

                print("Done polling")
                print(resp)
                
                sendSNS(key, ephem_id, status, satellite_id, execution_time)
                
                return {'ephemeris_id': ephem_id, status: status}
              
              else:
                print(f"Key: {key} is not the name of an ephemeris file processed by this function")

              return {'ephemeris_id': None}

          def sendSNS(key, ephem_id, status, satellite_id, execution_time):
              # SNS message
              print("Sending SNS notification.")
              snsclient = boto3.client('sns', region_name = os.environ.get("AWS_REGION"))
              now = datetime.now(timezone.utc).strftime("%I:%M%p %B %d, %Y")
              Txt1 = "Finished Processing file " + key + " for satellite: " + satellite_id
              Txt2 = ".     File uploaded on " + execution_time
              Txt3 = ".     Processing completed on " + now
              Txt4 = ".     The Ephemeris ID is " + ephem_id
              Txt5 = " and the status is " + status
              
              response = snsclient.publish(
                  TargetArn=os.environ.get("SNS_TOPIC"),
                  Message= Txt1 + Txt2 + Txt3 + Txt4 + Txt5,
                  Subject='Ground Station CPE Status',
              )

      Handler: index.handler
      Environment:
        Variables:
          TLE_KEY: !Sub 'configs/${SatelliteName}-tle.txt'
          OEM_KEY: !Sub 'configs/${SatelliteName}.oem'
          BUCKET: !Sub '${AWS::AccountId}-config-bucket-${SatelliteName}-${AWS::Region}'
          NORAD_ID: !Ref NoradId
          EXPIRATION: !Ref TleExpiration
          KMS_KEY: !GetAtt Key.Arn
          SNS_TOPIC: !Ref SNSTopic
          SATELLITE_ID: !Ref SatelliteId
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - 'groundstation:ListSatellites'
              Resource: !Sub 'arn:aws:groundstation:${AWS::Region}:${AWS::AccountId}:/satellite'
            - Effect: Allow
              Action: 
                - 'groundstation:CreateEphemeris'
              Resource: !Sub 'arn:aws:groundstation:${AWS::Region}:${AWS::AccountId}:/ephemeris'
            - Effect: Allow
              Action: 
                - 'groundstation:DescribeEphemeris'
              Resource: !Sub 'arn:aws:groundstation:*'
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
              Resource: !Sub 'arn:aws:s3:::${AWS::AccountId}-config-bucket-${SatelliteName}-${AWS::Region}/*'
            - Effect: Allow
              Action:
                - 'kms:Encrypt'
                - 'kms:Decrypt'
                - 'kms:GenerateDataKey*'
                - 'kms:DescribeKey'
                - 'kms:CreateGrant'
              Resource: !GetAtt Key.Arn
            - Effect: Allow
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: 'arn:aws:logs:*:*:*'
            - Effect: Allow 
              Action: 
                - "sns:Publish"
              Resource: !Ref SNSTopic

      Runtime: python3.9
      Timeout: 300

Outputs:
  BucketName:
    Value: !Ref ConfigBucket
    Description: Name of the S3 bucket that holds ephemeris. 
